name: random_number_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.2.3
  camera: ^0.11.3
  google_mlkit_image_labeling: ^0.14.1
  image_picker: ^1.2.0
  url_launcher: ^6.3.0
  flutter_typeahead: ^5.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg   # Your logo file